#!/bin/sh

case "$1" in
    start)
        echo "Loading misc-modules components"
        modprobe hello
        insmod /lib/modules/$(uname -r)/extra/faulty.ko
        ;;
    stop)
        echo "Unloading misc-modules components"
        rmmod faulty
        rmmod hello
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
